a

diff --git a/.github/workflows/Ubuntu.yml b/.github/workflows/Ubuntu.yml
--- a/.github/workflows/Ubuntu.yml
+++ b/.github/workflows/Ubuntu.yml
@@ -18,6 +18,11 @@ jobs:
       - name: Installing Ngrok ..
         run: sudo curl -sSL "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz" -o ngrok.tgz ; sudo tar -xzvf ngrok.tgz ; sudo rm ngrok.tgz ; sudo mv ngrok /usr/bin
       - name: Configuring Ngrok Token ..
-        run: ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
+        run: |
+          if [ -z "${{ secrets.NGROK_TOKEN }}" ]; then
+            echo "Error: Rahasia NGROK_TOKEN kosong atau belum diset di GitHub Secrets!"
+            exit 1
+          fi
+          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
       - name: Running Ngrok ..   
         run: ngrok http --domain=${{secrets.NGROK_DOMAIN}} 8080
